"""first migrate for user table

Revision ID: 4b42f59f67ea
Revises: 
Create Date: 2023-10-08 19:48:17.181096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b42f59f67ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_group',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_level', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('member_level')
    )
    op.create_table('permissions',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=200), nullable=False),
    sa.Column('permission_action', sa.String(length=200), nullable=False),
    sa.Column('permission_enable', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('member_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_level'], ['member_group.member_level'], ),
    sa.ForeignKeyConstraint(['member_level'], ['member_group.member_level'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('member_level', 'permission_action', name='uq_group_permission')
    )
    op.create_index(op.f('ix_permissions_permission_action'), 'permissions', ['permission_action'], unique=False)
    op.create_table('users',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('member_level', sa.String(length=50), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_login_attempt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_level'], ['member_group.member_level'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_permissions_permission_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('member_group')
    # ### end Alembic commands ###
